# Generated by Django 4.0.2 on 2022-05-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetAssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('long', models.DecimalField(decimal_places=10, max_digits=19)),
                ('short', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
