# Generated by Django 4.0.2 on 2022-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netassetvalue',
            name='asset',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
