# Generated by Django 4.0.2 on 2022-05-17 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0002_netassetvalue_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='netassetvalue',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
