# Generated by Django 4.0.2 on 2022-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0003_netassetvalue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netassetvalue',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
