# Generated by Django 4.0.2 on 2022-05-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0004_alter_netassetvalue_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkToMarketPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('assetClass', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=10, max_digits=19)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('position', models.DecimalField(decimal_places=10, max_digits=19)),
                ('transaction', models.DecimalField(decimal_places=10, max_digits=19)),
                ('commissions', models.DecimalField(decimal_places=10, max_digits=19)),
                ('other', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='netassetvalue',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
