# Generated by Django 4.0.2 on 2022-05-17 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0005_marktomarketperformancesummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealizedAndUnrealizedPerformanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('assetClass', models.CharField(max_length=100)),
                ('cost_adj', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rlz_ST_profit', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rlz_ST_loss', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rlz_LT_profit', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rlz_LT_loss', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unrlz_ST_profit', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unrlz_ST_loss', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unrlz_LT_profit', models.DecimalField(decimal_places=10, max_digits=19)),
                ('unrlz_LT_loss', models.DecimalField(decimal_places=10, max_digits=19)),
                ('date', models.DateField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
