# Generated by Django 4.0.2 on 2022-05-17 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0007_openpositions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cost_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('cost_Basis_HKD', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('value_HKD', models.DecimalField(decimal_places=4, max_digits=19)),
                ('unrealized_HKD', models.DecimalField(decimal_places=4, max_digits=19)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='marktomarketperformancesummary',
            name='commissions',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marktomarketperformancesummary',
            name='position',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marktomarketperformancesummary',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marktomarketperformancesummary',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='marktomarketperformancesummary',
            name='transaction',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='netassetvalue',
            name='long',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='netassetvalue',
            name='short',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='close_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='cost_price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='mult',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='unrealized_PL',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='openpositions',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='cost_adj',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='rlz_LT_loss',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='rlz_LT_profit',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='rlz_ST_loss',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='rlz_ST_profit',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='unrlz_LT_loss',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='unrlz_LT_profit',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='unrlz_ST_loss',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='realizedandunrealizedperformancesummary',
            name='unrlz_ST_profit',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
