# Generated by Django 4.0.2 on 2022-05-17 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0008_forexbalances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('assetClass', models.CharField(max_length=100)),
                ('date_Time', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=19)),
                ('trade_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('proceeds', models.DecimalField(decimal_places=4, max_digits=19)),
                ('comm_Fee', models.DecimalField(decimal_places=4, max_digits=19)),
                ('basis', models.DecimalField(decimal_places=4, max_digits=19)),
                ('realized_pl', models.DecimalField(decimal_places=4, max_digits=19)),
                ('mtm_pl', models.DecimalField(decimal_places=4, max_digits=19)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
