# Generated by Django 4.0.2 on 2022-05-17 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0009_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositsAndWithdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('report_date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
