# Generated by Django 4.0.2 on 2022-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0012_withholdingtax'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestAccruals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_reversal', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date', models.DateField()),
                ('ending_accrual_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('ending_accrual_balance_in_hkd', models.DecimalField(decimal_places=4, max_digits=19)),
                ('fx_translation', models.DecimalField(decimal_places=4, max_digits=19)),
                ('interest_accrued', models.DecimalField(decimal_places=4, max_digits=19)),
                ('starting_accrual_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('symbol', models.CharField(max_length=100)),
            ],
        ),
    ]
