# Generated by Django 4.0.2 on 2022-05-17 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0013_interestaccruals'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GBP', models.DecimalField(decimal_places=4, max_digits=19)),
                ('USD', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
