# Generated by Django 4.0.2 on 2022-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0015_registeredstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredstatement',
            name='filename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
