# Generated by Django 4.0.2 on 2022-05-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0016_registeredstatement_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
