# Generated by Django 4.0.2 on 2022-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0020_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.RemoveField(
            model_name='document',
            name='a',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
    ]
