# Generated by Django 4.0.2 on 2022-05-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0021_delete_user_profile_remove_document_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='uploaded',
        ),
    ]
