# Generated by Django 4.0.2 on 2022-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0022_rename_uploaded_at_document_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded',
            new_name='uploaded_at',
        ),
    ]
