# Generated by Django 4.0.2 on 2022-05-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statementReader', '0023_document2_rename_uploaded_document_uploaded_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document2',
        ),
    ]
